# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkaP0fWuo0hDWYdYX094COcy3Ig07qga
"""

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qr requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pwd

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

!pip install roboflow

from roboflow import Roboflow

rf = Roboflow(api_key="doQ4urpD6jI4ynbgOA81")
project = rf.workspace("nupur02").project("apple_and_mango_dataset")
version = project.version(1)
dataset = version.download("yolov5")

!python train.py --img 416 --batch 10 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# Start tensorboard
# Launch after you have started training
# logs save in the folder "runs"
# %load_ext tensorboard
# %tensorboard --logdir runs

# source /path ---> images
# source 0 -----> webcam
# source /path of video
# source ---> url of youtube

!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source {dataset.location}/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

